apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-agents
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: test.clab.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-agents
                port:
                  number: 80
  tls:
    - hosts:
        - test.clab.one
      secretName: test-agents-tls
